### ISSUE TITLE
Need support for new T-series devices

### ISSUE THREAD

**Issue by rolsen** [labjack/exodriver#20]
The ill-named [t4 branch](https://github.com/labjack/exodriver/tree/t4) adds untested T4 support. @davelopez01, please test before merging, of course.

Also, we should probably just add T5 support now, so we only have to increment the version once. Do you agree, @davelopez01?

**Comment by davelopez01** [comment]
I agree, we should add in the T5 as well. You want to add that in your t4 branch?

**Comment by davelopez01** [comment]
Merged your T4 changes from the T4 branch and I added T5 support. Should be ready for LJM. Thanks @rolsen .
