### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by birkenfeld** [labjack/exodriver#27]
The last tag is from 2014, with quite a few commits since. Would it make sense to create a new tagged release?

Thanks!

**Comment by davelopez01** [comment]
Thanks for bringing this up. I made a tag for release v2.6.0.

**Comment by birkenfeld** [comment]
Great, thanks!

I've since noticed the same in the LabJackPython repo, there is mention of versions 2.0.1-4 in the readme but they aren't tagged or uploaded to PyPI.  Should I make an issue there?

**Comment by davelopez01** [comment]
You can if you like, but I will make a todo on our end to make a tag and release. Current plan is just to do one for 2.0.4. That will probably get done next week.

**Comment by birkenfeld** [comment]
That's good enough for me, thanks!

**Comment by davelopez01** [comment]
LabJackPython 2.0.4 has been tagged on GitHub, and released on PyPI and labjack.com.
